function nwb = GeneralInfo(xml)
    % Adds info in: nwb.general_subject

    %% General Info
    nwb_version = '2.0b';

    session_start_time = datetime(xml.generalInfo.date.Text, ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ssZZ', ...
        'TimeZone', 'local');
    timestamps_reference_time = datetime(xml.generalInfo.date.Text, ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ssZZ', ...
        'TimeZone', 'local');

    file_create_date = datetime(datestr(clock), ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ssZZ', ...
        'TimeZone', 'local');

    nwb = nwbfile( ...
        'session_description'          , 'Mouse in open exploration and theta maze', ...
        'identifier'                   , xml.name, ...
        'session_start_time'           , session_start_time,...
        'file_create_date'             , file_create_date,...
        'general_experimenter'         , xml.generalInfo.experimenters.Text,...
        'general_session_id'           , xml.name,...
        'general_institution'          , 'NYU'  ,...
        'general_lab'                  , 'Buzsaki',...
        'subject'                      , 'YutaMouse',...
        'general_related_publications' , 'DOI:10.1016/j.neuron.2016.12.011',...
        'timestamps_reference_time'    , session_start_time);

    nwb.general_subject = types.core.Subject( ...
        'description', 'mouse 5', 'genotype', 'POMC-Cre::Arch', 'age', '9 months', ...
        'sex', 'M', 'subject_id', xml.name, 'species', 'Mus musculus');

    disp('General info added..')
end